# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25, verbose_name='User Name')),
                ('commment', models.CharField(max_length=250, verbose_name='Comment')),
                ('date_created', models.DateField(verbose_name='Created Date')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('summary', models.CharField(max_length=500, verbose_name='Summary')),
                ('content', models.TextField(max_length=1000, verbose_name='Content')),
                ('date_created', models.DateField(verbose_name='Created Date')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
    ]
